import test from 'node:test';
import assert from 'node:assert/strict';
import {Game,overlap} from '../docs/js/engine.js';
import {freshSave,validateSave,STAGES,STEP} from '../docs/js/levels.js';
import {SCORES,Sound} from '../docs/js/audio.js';
const make=(id=0)=>{const s=freshSave();s.cleared=[0,1,2];const g=new Game(s);g.load(id);g.enemies=[];return g;};
const ticks=(g,n,input={})=>{for(let i=0;i<n;i++)g.tick(STEP,input);};
for(const id of [0,1,2,3])test(`stage ${id}: only matching projectiles activate devices and create routes`,()=>{
 const g=make(id);for(const d of g.devices){const shot=weapon=>{g.bullets=[{x:d.x,y:d.y+15,w:12,h:12,vx:0,vy:0,life:1,weapon,damage:2,color:'#fff',hitIds:new Set()}];g.updateBullets(STEP);};
 shot('pulse');assert.equal(d.active,false);shot(d.weapon);assert.equal(d.active,true);assert.ok(g.solidsFor({x:d.bridge.x,y:d.bridge.y,w:40,h:40}).some(s=>s.x===d.bridge.x&&s.y===d.bridge.y));if(d.kind==='relay')assert.ok(g.level.hazards.filter(h=>h.x>d.x).every(h=>h.disabled));if(d.kind==='icewall')assert.ok(!g.solidsFor(d).includes(d));}
});
test('returning boomerang bypasses frontal shield and hits the back once',()=>{const g=make();const e={x:180,y:374,w:34,h:42,type:'shield',face:-1,hp:6,frozen:0,dead:false};g.enemies=[e];g.player.x=100;g.player.y=376;g.equipWeapon('arc');g.fire();for(let i=0;i<15;i++)g.updateBullets(STEP);assert.equal(e.hp,6);for(let i=0;i<80;i++)g.updateBullets(STEP);assert.equal(e.hp,4);assert.equal(g.bullets.length,0);});
test('flame wheel rolls on floor and pierces consecutive armored enemies',()=>{const g=make();g.player.x=100;g.player.y=376;g.enemies=[200,320].map(x=>({x,y:378,w:34,h:42,type:'shield',face:-1,hp:6,frozen:0,dead:false}));g.equipWeapon('flame');g.fire();for(let i=0;i<40;i++)g.updateBullets(STEP);assert.ok(g.bullets[0]?.ground);assert.deepEqual(g.enemies.map(e=>e.hp),[4,4]);assert.ok(g.bullets[0].y+g.bullets[0].h<=420);});
test('frozen flying enemy becomes a safe platform, then thaws',()=>{const g=make();const e={x:200,y:280,w:30,h:24,type:'drone',startX:200,startY:280,hp:8,dead:false,frozen:0,slow:0,hit:0,time:0,cooldown:10};g.enemies=[e];g.player.x=158;g.player.y=264;g.equipWeapon('frost');g.fire();g.updateBullets(STEP);assert.ok(e.frozen>3);g.player.x=201;g.player.y=230;g.player.vy=200;g.player.invincible=0;g.move(g.player,.04,true);assert.equal(g.player.y,236);assert.ok(g.player.ground);const hp=g.player.hp;g.updateEnemies(.1);assert.equal(g.player.hp,hp);g.updateEnemies(4);assert.equal(e.frozen,0);});
test('weapon energy is independent, locked weapons cannot be equipped',()=>{const g=make();g.equipWeapon('arc');g.fire();assert.equal(g.player.energy,25);g.equipWeapon('flame');assert.equal(g.player.energy,28);g.fire();assert.equal(g.player.energy,24.5);g.equipWeapon('arc');assert.equal(g.player.energy,25);g.equipWeapon('pulse');assert.equal(g.player.energy,28);const locked=new Game(freshSave());assert.equal(locked.equipWeapon('arc'),false);});
test('route upgrade is gated, permanent, unique across retry and old-save compatible',()=>{const g=make(1),i=g.items.find(i=>i.type==='upgrade'),p=g.player;g.level.hazards=[];p.x=i.x;p.y=i.y;p.vy=0;g.tick(STEP,{});assert.equal(g.save.upgrades.length,0);g.activateDevice(g.devices[0],'arc');p.x=i.x;p.y=i.y;p.vy=0;g.tick(STEP,{});assert.deepEqual(g.save.upgrades,[1]);assert.equal(p.maxHp,22);g.retry();assert.equal(g.player.maxHp,22);assert.equal(g.items.filter(i=>i.type==='upgrade').length,0);assert.deepEqual(validateSave({version:1}).upgrades,[]);assert.deepEqual(validateSave({version:1,upgrades:[1,1,8,-1,'2']}).upgrades,[1]);});
for(const id of [0,1,2,3])test(`boss ${id}: every unique attack executes and ends its tell`,()=>{for(const action of STAGES[id].patterns){const g=make(id),b=g.boss;b.active=true;b.state='idle';b.pattern=STAGES[id].patterns.indexOf(action);b.timer=0;g.player.x=4700;g.player.invincible=100;g.updateBoss(STEP);assert.equal(b.action,action);b.timer=0;g.updateBoss(STEP);assert.notEqual(b.state,'tell');assert.ok(['rush','dive','leap'].includes(b.state)||g.enemyBullets.length||g.dangerZones.length,action);for(let i=0;i<70;i++)g.updateBoss(STEP);assert.ok(Number.isFinite(b.x)&&Number.isFinite(b.y));}});
test('boss weakness doubles damage and interrupts the attack',()=>{const g=make(1),b=g.boss;b.active=true;b.state='tell';b.hit=0;g.bullets=[{x:b.x,y:b.y+20,w:20,h:20,vx:1,vy:0,life:1,damage:2,weapon:'arc',hitIds:new Set(),color:'#fff'}];g.updateBullets(STEP);assert.equal(b.hp,b.maxHp-4);assert.equal(b.state,'stagger');});
test('danger zones cannot damage during warning and expire after attack',()=>{const g=make();g.player.invincible=0;g.dangerZones=[{x:g.player.x,y:g.player.y,w:40,h:50,tell:.4,life:.2,color:'#fff'}];const hp=g.player.hp;g.updateDangerZones(.3);assert.equal(g.player.hp,hp);g.updateDangerZones(.11);assert.equal(g.player.hp,hp);g.updateDangerZones(.05);assert.ok(g.player.hp<hp);g.updateDangerZones(.2);assert.equal(g.dangerZones.length,0);});
test('stage scores are different complete 16-bar melodies and schedule safely',()=>{assert.equal(new Set([0,1,2,3,'boss'].map(k=>SCORES[k].lead.join(','))).size,5);for(const [key,score] of Object.entries(SCORES)){assert.equal(score.lead.length,key==='victory'?32:128);assert.ok(score.lead.every(n=>n===null||Number.isFinite(n)));const sound=new Sound();sound.ctx={currentTime:0,state:'running'};sound.track=key;sound.next=0;const calls=[];sound.tone=(...args)=>calls.push(args);sound.hiss=(...args)=>calls.push(args);sound.schedule();assert.ok(calls.length>=3);assert.ok(sound.step>0);const count=calls.length;sound.paused=true;sound.schedule();assert.equal(calls.length,count);sound.paused=false;sound.muted=true;sound.schedule();assert.equal(calls.length,count);}});
